Makefile, examples/workflows/cockroach_dedicated_cluster/main.tf, examples/workflows/cockroach_serverless_cluster/main.tf
- Correcting 0.3.2 version in Makefile
- fixing incorrect path for provider in workflow examples
Our workflow examples call for path "hashicorp/cockroach" but the registry page points to a different path "cockroachdb/cockroach". Somehow the version obtained via the incorrect path is 0.3.2 - i'm guessing it's getting that version from the Makefile, which specifies version 0.3.2.
If one uses the correct path, the correct version is shown in `terraform init` - so the change to the Makefile may be unnecessary. 
**Checklist**
=> Correcting 0.3.2 version in Makefile and fixing provider path in workflow examples

.gitignore, go.mod, go.sum, internal/provider/networking_resource.go, internal/provider/provider.go
- Updated the CCAPI client library to v0.3.1.
- Renamed "networkResource" to "allowListResource" to avoid ambiguity with other resources, such as PrivateLink specs.
- Updated the UpdateAllowList input to match new simplified format.
No user-facing changes. This just paves the way for new resources to be added later.
Ran the examples and verified they still work.
=> Update to Go SDK v0.3.1

docs/resources/allow_list.md, docs/resources/sql_user.md, examples/resources/cockroach_ip_allowlist/cockroach_ip_allowlist.tf, examples/resources/cockroach_sql_user/cockroach_sql_user.tf, examples/workflows/cockroach_dedicated_cluster/main.tf, examples/workflows/cockroach_serverless_cluster/main.tf, internal/provider/cluster_resource.go, internal/provider/models.go, internal/provider/networking_resource.go, internal/provider/networking_resource_test.go, internal/provider/provider_test.go, internal/provider/sql_user_resource.go, internal/provider/sql_user_resource_test.go, internal/provider/utils.go
- Fixed import by composing a unique ID for both resources
- Renamed the old id to cluster_id
- Implemented Read with an API call instead of copying the state
- Cleaned up error message formatting
- Updated test provider to use COCKROACH_SERVER
- Consolidated SQL user models
- Reran `go generate`
- Pull misconfigured provider error into util function
=> Clean up SQL User and Allowlist resources

internal/provider/networking_resource.go
Since the ID is based on the CIDR address, it needs to be recomputed when the address is updated.
=> Force allowlist rebuild when address is changed

docs/resources/private_endpoint_connection.md, examples/workflows/aws_privatelink/main.tf, internal/provider/private_endpoint_connection_resource.go
Just a quick change to support `import` for connections, even though it probably won't be used often. Follows the same pattern as SQL users. Tested manually, and tested import for services too. I also added a warning comment to the example, since region is configured at the provider level for AWS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/45)
=> Fixed endpoint connection import and annotated example

internal/provider/cluster_resource.go, internal/provider/networking_resource.go, internal/provider/sql_user_resource.go
- Name and provider updates no long require replace, but result in a runtime error asking the user to explicitly delete them first if that's what they intended.
- Orthogonal fix: If we can't find a resource on Read, delete it from state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/47)
=> Disallow cluster name and provider updates

internal/provider/cluster_resource.go
Users can still pass in a value of zero. It just can't be null, to avoid state errors. We might be able to make it optional again after implementing ModifyResource, but that's a larger change for another day.
=> Require spend limit

internal/provider/cluster_resource.go, internal/provider/networking_resource.go, internal/provider/private_endpoint_connection_resource.go, internal/provider/private_endpoint_services_resource.go, internal/provider/sql_user_resource.go
Apparently, using an error will prevent any state changes. We need to use a warning instead. I also noticed that we're not correctly updating state in Read for allowlist entries and endpoint services, so fixed that.
=> Fix state updates on read for missing resources

internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go, internal/provider/private_endpoint_services_resource_test.go
Previously, we attempted to copy over cluster state while polling for status, but accidentally overrode the local pointer address instead of the object itself. This change copies the cluster over. Added test cases for cluster and endpoint services, which behaves the same way.
=> Fix cluster state on initial creation

examples/workflows/cockroach_dedicated_cluster/main.tf, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go
Transform version strings from API results into the format we expect for cluster creation.
Also moved the dedicated test cluster to GCP and us-central1 since it's a little bit cheaper and closer to our control plane.
=> Fix inconsistent result error when using cockroach_version

examples/workflows/cockroach_dedicated_cluster/main.tf
Also, the previous hard-coded value wasn't valid. The new default is.
=> Change cockroach_version in examples to variable

internal/provider/cluster_resource.go, internal/provider/models.go, internal/provider/private_endpoint_connection_resource.go, internal/provider/private_endpoint_services_resource.go
Cluster update operations can take a pretty long time, especially multiregion clusters. We had an SE bump into the timeout, even though it was still chugging along. Bumped it to 2 hours. Dropped the endpoint connection timeout to 10 minutes (usually completes in ~30s). Left cluster and endpoint service creation unchanged.
Generally refactored timeout constants, and also a couple unrelated cluster state constants that were hard coded and at risk of going out of sync with the API.
Also opportunistically fixed a fixed a segfault that happened if a call to GetCluster fails in the wait loop, trying to copy the value of a nil cluster pointer.
=> Update timeouts and clean up constants

internal/provider/cluster_resource.go, internal/provider/cockroach_cluster_data_source.go, internal/provider/networking_resource.go, internal/provider/private_endpoint_connection_resource.go, internal/provider/private_endpoint_services_resource.go
Attempted to audit all calls to diagnostics.AddError to ensure that the error messages are accurate and follow a consistent formatting scheme, according to https://developer.hashicorp.com/terraform/plugin/log/writing. Standardized on "allowlist" instead of "allow list".
Also cleaned up some obsolete comments and validation checks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/62)
=> Audit error reporting

terraform-registry-manifest.json
This was reported by our friends at Nightfall. Our registry manifest says we use protocol version 5.0 (which is what the TF SDK v2 uses), but we're using the plugin framework, which uses protocol version 6.0.
=> update manifest protocol version

examples/workflows/cockroach_dedicated_cluster/main.tf
Now that v22.2 is GA, bump the default version to v22.2 in the dedicated workflow example.
=> Bump default CRDB dedicated version to v22.2

internal/provider/cockroach_cluster_data_source.go, internal/provider/networking_resource.go, internal/provider/sql_user_resource.go
- Fixed an initialization bug for datasources. It was attempting to use resource types and didn't match the Configurable interface.
- Fixed a bug where users were unable to delete allowlist and SQL user resources if the cluster had disappeared.
=> Misc bug fixes

go.mod, go.sum, internal/provider/cluster_resource.go
Started making use of some of the extended resource functionality
the framework provides, namely ConfigValidators and ModifyPlan.
ConfigValidators let you validate a config
by itself. You can do stuff like prevent conflicting attributes
(dedicated and serverless in this case).
ModifyPlan seems to be intended to handle things like default values,
but I'm using it to prevent users from making certain changes to
clusters. All of the apply-time validation baked into Update now
lives in this method, as well as validation for the scenario in
the commit title.
Updated the framework to v1.1.1 (hooray stability!) to make use of
ConfigValidators. No changes were necessary. The changelog suggests
that they only removed some deprecated code with the 1.0 update.
- - -
This change is [<img …
=> [CC-9116] Cluster resource allows network visibility to be toggled after creation

internal/provider/networking_resource.go, internal/provider/networking_resource_test.go
Fixed a logic error where we were checking if the IP address _OR_ the CIDR mask matched instead of the address _AND_mask. Added a regression test.
=> Allowlist resource matches wrong entry on Read

docs/resources/sql_user.md, internal/provider/sql_user_resource.go, internal/provider/sql_user_resource_test.go
Previously, password was a required field for SQL users. This caused
import problems because we can't read and set the password (nor do
we want to).
This change makes it optional, and if it's omitted, we randomly
generate a 32-character random password. This password isn't saved
to state, though. The user needs to then change it via the web UI.
Setting the password field to null after the resource is created
will not change the password, but makes Terraform forget it.
=> Make SQL User password optional and generate of omitted

docs/resources/cluster.md, internal/provider/cluster_resource.go
@alistair-roacher noticed that the docs mentioned PrivateLink requiring private networking when it is not required.
=> private_networking_visibility description change - remove PrivateLink as the flag is not required 

.github/workflows/ci.yaml
Previously, the golangci-lint action failed because
it installed the latest stable go version instead of
using the pre installed version. Now it uses the
pre installed go version 1.18.
=> bump action versions for ci workflow

examples/workflows/cockroach_cmek/aws/main.tf
Apparently, this condition is no longer advised and can cause backups to fail. It was removed from the docs shortly after this example was added.
=> Remove ExternalId condition from AWS CMEK role policy

internal/provider/cluster_resource.go
Previously, if a cluster was deleted outside of Terraform, whether by a user action or a sweeper, attempting to delete it in Terraform would result in a "cannot delete locked cluster" error. This is only an issue for the cluster resource because GET /cluster doesn't return a 404 like most other endpoints and users can still retrieve details about deleted clusters. We just need to check the status.
=> Remove deleted clusters from state

docs/resources/cluster.md, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go, internal/provider/models.go
This change adds a `Primary` field to the region schema, which is required when creating multi-region serverless clusters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/99)
=> [CC-7610] support creating multi-region serverless clusters

.github/workflows/ci.yaml
Add explicit setup-go for golangci-lint-action as directed in
https://github.com/golangci/golangci-lint-action#compatibility
=> Add explicit setup-go for golangci-lint-action

internal/provider/cluster_resource_test.go
Use a different machine type for dedicated
cluster acceptance test.
=> update dedicated cluster test

internal/provider/cluster_resource.go
Previously, we assumed that all update operations were initiated by the user through Terraform, but it turns out that there are a number of locking jobs that are run automatically, like minor version upgrades. These are usually fairly short, but can still cause Terraform operations to fail.
This commit adds a wait to cluster update and delete actions if the cluster is locked. Since Terraform always performs a Read before Update or Delete, it's safe to check the cluster status in the Terraform state.
=> Wait for lock to release on cluster update and delete

internal/provider/cluster_resource_test.go
This reverts commit 12a16f9cf7d44a7112ec39fd7396c7f871a59cb2.
Now that the external issue with the lower cost
machine type is fixed, revert to use it again.
=> Revert "update dedicated cluster test (#103)"

Makefile, docs/data-sources/cluster.md, docs/resources/cluster.md, examples/workflows/cockroach_cmek/gcp/main.tf, go.mod, go.sum, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go, internal/provider/cmek_resource_test.go, internal/provider/cockroach_cluster_data_source.go, internal/provider/database_resource.go, internal/provider/models.go, vendor/github.com/cockroachdb/cockroach-cloud-sdk-go/pkg/client/model_api_database.go, vendor/github.com/cockroachdb/cockroach-cloud-sdk-go/pkg/client/model_usage_limits.go, vendor/modules.txt
The Cockroach Cloud API now supports a way to limit the number of request units and storage MiB that a cluster can use. This works alongside an existing limit on the $ spend a cluster can incur. A caller can choose to either specify resource limits or a spend limit, but not both. If neither is specified, then the cluster will not have any limits enforced.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/108)
=> Add support for resource limits

internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go
Previously, we only allowed the magic string "preview" to create new clusters with a preview crdb build. Now, the API supports cluster creation with the major version of the requested preview. That means the Terraform cluster won't get into a bad state once the version moves out of preview. This change attempts to match the version format of the state to the version format of the config when using preview versions.
=> Support explicit preview CRDB versions

CHANGELOG.md, README.md
It looks like some formatting was lost on the list of variable descriptions for the examples in the README.  I've added trailing double spaces after these lines to linebreak them.
Previously:
After this PR:
=> Improve README variable description formatting

docs/resources/cluster.md, docs/resources/cmek.md, internal/provider/cluster_resource.go
If a dedicated cluster has a primary region, the plan that's created doesn't match the state of the cluster. This change creates an error if a dedicated cluster's region is marked as primary, and adds some documentation to specify that only serverless regions should me marked primary.
Fixes #113
=> Do not allow dedicated regions to be marked primary

README.md, docs/index.md, examples/provider/provider.tf
Previously the pages and files below included a broken link to the Console Access Management page:
* https://registry.terraform.io/providers/cockroachdb/cockroach/latest/docs
* [/docs/index.md](https://github.com/cockroachdb/terraform-provider-cockroach/blob/main/docs/index.md)
* [/README.md](https://github.com/cockroachdb/terraform-provider-cockroach/blob/main/README.md)
The broken link was pointing to 
```
https://www.cockroachlabs.com/docs/cockroachcloud/console-access-management#api-access
```
but by adding `.html` as suffix on the url, the link now works again: 
```
https://www.cockroachlabs.com/docs/cockroachcloud/console-access-management.html#api-access
```
=> Fixed broken links to console access management page

internal/provider/sql_user_resource.go
At present, the provider does not use pagination to retrieve the list of existing SQL users when verifying that a user in the state actually exists. As such, the provider pulls only the first page of SQL users
Subsequently, a cluster with a large number of SQL users will end up with warnings during each Terraform run of `This cluster doesn't have a SQL user named... Removing from state.`. Attempting to apply will end up with the provider erroring as it attempts to create new users that conflict with existing ones.
=> Fix absent pagination when retrieving existing SQL users

internal/provider/cluster_resource.go, internal/provider/log_export_config_resource.go, internal/provider/metric_export_cloudwatch_config_resource.go, internal/provider/metric_export_datadog_config_resource.go
Fix for https://github.com/cockroachdb/terraform-provider-cockroach/issues/117
Previously, log and metric export changes competed 
for the cluster lock and failed if it was not
available. Now, they wait for the cluster lock's
release before retrying. Read for these resources 
also now handles deleted clusters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/127)
=> Add cluster checks to log and metric export resources

DEVELOPMENT.md, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go
Fixes https://github.com/cockroachdb/terraform-provider-cockroach/issues/131. Regression from https://github.com/cockroachdb/terraform-provider-cockroach/pull/108.
This commit fixes a panic when trying to import a serverless cluster through
terraform. We were originally reading from `clusterObj.Config.Serverless`, but
after https://github.com/cockroachdb/terraform-provider-cockroach/pull/108, we end up checking on `plan.ServerlessConfig`, which is incorrect.
=> internal/provider: fixes a panic when trying to import a serverless cluster

internal/provider/networking_resource.go, internal/provider/networking_resource_test.go
Previously, we disallowed network allowlist usage for serverless clusters. Now
that CockroachCloud supports this feature for all serverless clusters, we will
remove that guard, and this commit does that.
=> internal/provider: add network allowlist support for serverless clusters

internal/provider/networking_resource_test.go, internal/provider/private_endpoint_connection_resource.go, internal/provider/private_endpoint_connection_resource_test.go, internal/provider/private_endpoint_services_resource.go, internal/provider/private_endpoint_services_resource_test.go
Previously, we disallowed private endpoints support for serverless
clusters. Now that CockroachCloud supports this feature for all serverless
clusters, we will remove that guard, and this commit does that.
=> intrusion/provider: add private endpoints support for serverless clusters

CHANGELOG.md, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go, internal/provider/cockroach_cluster_data_source.go, internal/provider/utils.go
- Changed cluster datasource to use loadClusterToTerraformState to share code with the resource
- Added import steps to dedicated cluster tests
- Added datasources to configs for all cluster tests
- Added a test to make sure cluster resource and datasource stay in sync
I'm planning on a followup PR to add similar tests for other resources/datasources.
=> [CC-25142] Cluster tests for import and datasource

internal/provider/private_endpoint_services_resource_test.go
This would ensure that we create the acceptance cluster on the multi-region
host in production, which has PrivateLink supported, provided that the 
organization has the right feature flag turned on.
=> internal/provider: fix TestAccServerlessPrivateEndpointServicesResource

internal/provider/client_ca_cert_resource_test.go, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go, internal/provider/cmek_resource_test.go, internal/provider/log_export_config_resource_test.go, internal/provider/maintenance_window_test.go, internal/provider/metric_export_cloudwatch_config_resource_test.go, internal/provider/metric_export_datadog_config_resource_test.go, internal/provider/networking_resource_test.go, internal/provider/private_endpoint_connection_resource_test.go, internal/provider/private_endpoint_services_resource_test.go, internal/provider/version_deferral_test.go
- Updated cluster state import logic to check the plan for which limit type to set
- Updated tests that use machine_type to use num_virtual_cpus instead, for futureproofing
Running tests manually now. Will make sure they're passing before merging.
=> Test fixes

internal/provider/private_endpoint_services_resource_test.go
**NOTE: Only merge this end of the week.**
----
Previously, we asserted that the private endpoint services returned by the
server span all regions of the host (for a serverless cluster), and not just
the regions of the serverless cluster. This was a bug in CockroachCloud itself,
and has already been addressed there. This commit updates that assertion to
the number of regions on the serverless cluster, addressing a TODO.
=> internal/provider: address a test TODO for private endpoint services

docs/data-sources/cluster.md, docs/resources/cluster.md, docs/resources/cmek.md, internal/provider/cluster_resource.go, internal/provider/cockroach_cluster_data_source.go, internal/provider/models.go
Previously, there was no way to obtain the internal_dns field via the
terraform provider; the CC API does return the internal_dns field. This
commit updates the provider to include that field so that users could use it
for VPC Peering or AWS PrivateLink.
=> internal/provider: expose the internal_dns field within the region model

internal/provider/client_ca_cert_resource_test.go, internal/provider/cluster_cert_data_source.go, internal/provider/cluster_cert_data_source_test.go, internal/provider/cmek_resource_test.go, internal/provider/connection_string_data_source_test.go, internal/provider/database_resource_test.go, internal/provider/log_export_config_resource_test.go, internal/provider/maintenance_window_test.go, internal/provider/metric_export_cloudwatch_config_resource_test.go, internal/provider/metric_export_datadog_config_resource_test.go, internal/provider/networking_resource_test.go, internal/provider/organization_data_source_test.go, internal/provider/person_user_data_source_test.go, internal/provider/private_endpoint_connection_resource_test.go, internal/provider/private_endpoint_services_resource_test.go, internal/provider/role_resource_test.go, internal/provider/sql_user_resource_test.go, internal/provider/version_deferral_test.go
Made sure all resources and data sources have tests. Added import steps to resources that didn't already have one.
- [n/a] Changelog
- [n/a] Doc gen (`make generate`)
- [n/a] Example(s)
=> [CC-52142] Add tests for data sources and resource import

CHANGELOG.md, examples/workflows/cockroach_dedicated_cluster/main.tf, internal/provider/allowlist_resource.go, internal/provider/client_ca_cert_resource.go, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go, internal/provider/cmek_resource.go, internal/provider/connection_string_data_source.go, internal/provider/log_export_config_resource.go, internal/provider/metric_export_cloudwatch_config_resource.go, internal/provider/sql_user_resource.go, internal/provider/utils.go
Previously, we used the config instead of the plan for create and update operations and were able to simply check for null values. Now we use the plan, but that means we need to check if values are either null or unknown.
This change adds a utility method that checks both. Replaced all references to both states, since in all existing cases, we want to treat them the same.
Refactored the cluster resource integration tests to allow any number of GetCluster calls and return the latest iteration of the cluster after UpdateCluster mutates it.
This fixes issue #152.
=> Check both IsNull and IsUnknown in plan

CHANGELOG.md, internal/provider/cluster_resource.go
Previously, the primary_region field used a `UseStateForUnknown` plan modifier, but that wasn't actually doing anything because we were checking the config instead of the plan. Now that we're checking the plan instead, the modifier is retaining the attribute's previous value when unknown (removed from the config). That was causing the previous primary region to still be marked as primary, and there was no validation to ensure that only one primary region is specified.
This change removes the plan modifier and adds validation to protect against multiple primaries.
=> Fix TestAccMultiRegionServerlessClusterResource

.github/workflows/pre-release-ci.yaml, .github/workflows/release.yml
Previously, we run the release workflow automatically whenever a v* tag
gets pushed. The existing workflow does not work because the tests can be
flaky. When that happens, there's no way to release a new TF version since
goreleaser will only run once all the acceptance tests pass.
Until the flakiness goes away, we will split the release workflow into
two: pre-release-ci (that runs automatically like before), and release (which
has to be triggered manually after all the acceptance tests are triaged).
=> .github/workflows: split release into pre-release-ci and release (manual)

examples/workflows/cockroach_dedicated_cluster/main.tf
cockroach_version requires a feature flag to be set even if the version is set to the latest version.  Customers who use this example nearly always run into this issue. Removing this block since its not core to the example.
For now, I've left out any docs changes.
=> Remove cockroach_version from the dedicated example

CHANGELOG.md, internal/provider/utils.go
We use a custom retryable http client to retry GET requests. Since it is intended to only retry GET requests we check that the request was a GET at the beginning of the method.  The only way to access the request at this point in the code is through the response object, however, there are some cases where this  object is nil.  This was resulting in a nil pointer exception.
After this change, any errors that are seen without a set Response object will fall through to the default handler.
Fixes a Nil pointer exception reported here:
https://cockroachlabs.slack.com/archives/C01J7MGJ3S7/p1696613858625329?thread_ts=1696613850.476459&cid=C01J7MGJ3S7
- ✔️  Changelog
=> defer to base retry check when response is nil

CHANGELOG.md, examples/workflows/cockroach_dedicated_cluster/main.tf, internal/provider/log_export_config_resource.go
Currently, the "redact" field in the individual log groups is declared as a "computed" field. When a field is marked as "computed", user removing the field/commenting it out is sometimes not recognised as a "diff" in terraform state. This makes it look like the "redact" field is not working
---
Applied this configuration of the `log_exporter`
Does not show a diff when `redact` is commented out in the second log group
Shows the expected diff
=> log-export: make group specific redact noncomputed

CHANGELOG.md, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go
Previously, the TF provider raised an error when the primary attribute was specified in multiple regions, e.g.:
regions = [
{
name    = "eu-west-1"
primary = true
},
{
name    = "eu-west2"
primary = false
},
{
name    = "ap-south-1"
primary = false
},
]
This PR fixes that by adding some custom validation logic rather than using the built-in config validators.
Fixes: CC-27160
=> fix error when primary attribute is specified in multiple regions

CHANGELOG.md, internal/provider/provider.go
Previously, enabling debug for the tf provider did not log out requests. The cloud sdk already supported a debug mode. We now enable this via configuration if one of the terraform debug env vars (TF_LOG_PROVIDER or TF_LOG) are set to either "DEBUG" or "TRACE".
=> enable request logging when debug is enabled

CHANGELOG.md, docs/resources/private_endpoint_connection.md, examples/resources/cockroach_aws_private_endpoint_connection/resource.tf, internal/provider/private_endpoint_connection_resource.go, internal/provider/private_endpoint_connection_resource_test.go
Previously, the private_endpoint_connection resource only supported AWS
private link connections. This commit updates the provider code to use
the new CC API Private Endpoint Connections methods. These cloud-neutral
methods will work for all cloud providers and cluster types, except
Serverless clusters on Azure as that configuration is not yet
supported.
=> Use new private endpoint connections API

CHANGELOG.md, docs/resources/private_endpoint_services.md, internal/provider/cluster_resource_test.go, internal/provider/models.go, internal/provider/private_endpoint_services_resource.go
Previously, the private_endpoint_services resource only supported the creation of AWS private endpoint services. This commit removes this restriction, now all clouds are supported. Additionally this commit fixes a bug that caused the private_endpoint_service resource to be created without the resource state being loaded into the state file. Lastly, this commit bumps the CRDB version used for testing.
=> private endpoint services: support all clouds

CHANGELOG.md
Updated the changelog for the 1.4.0 release. 
I ran the full test suite against a staging org.  The tests that didn't pass all looked to be because of various feature flags that weren't flipped on my org.  The tagging process will run the tests again.
=> Update changelog for 1.4.0 release

internal/provider/allowlist_resource_test.go, internal/provider/client_ca_cert_resource_test.go, internal/provider/cluster_cert_data_source_test.go, internal/provider/cluster_resource_test.go, internal/provider/cmek_resource_test.go, internal/provider/connection_string_data_source_test.go, internal/provider/database_resource_test.go, internal/provider/folder_data_source_test.go, internal/provider/folder_resource_test.go, internal/provider/log_export_config_resource_test.go, internal/provider/maintenance_window_test.go, internal/provider/metric_export_cloudwatch_config_resource_test.go, internal/provider/metric_export_datadog_config_resource_test.go, internal/provider/private_endpoint_connection_resource_test.go, internal/provider/private_endpoint_services_resource_test.go, internal/provider/private_endpoint_trusted_owner_resource_test.go, internal/provider/sql_user_resource_test.go, internal/provider/user_role_grant_resource_test.go, internal/provider/utils.go, internal/provider/version_deferral_test.go
Prefixing the cluster names with "tftest" makes them easier to find in case they are failed to be cleaned up. Most were already prefixed that way. This change updates the remaining few that were not.
=> ensure all test cluster names have tftest prefix

CHANGELOG.md, docs/resources/private_endpoint_connection.md, examples/resources/cockroach_private_endpoint_connection/resource.tf, internal/provider/private_endpoint_connection_resource.go
Adds more detailed docs for the `private_endpoint_connection` resource.
=> docs: add docs for private endpoint connections

.github/workflows/ci.yaml
Add a github workflow that runs make generate and fails if there are any changes.
example failure:
=> Add docs check

CHANGELOG.md, docs/resources/allow_list.md, internal/provider/allowlist_resource.go, internal/provider/allowlist_resource_test.go, internal/provider/cluster_resource_test.go, internal/provider/utils.go
Previously, allowlist.name attribute was not marked as computed so values from the server would not set the state in case it was unused. The server side default of "" would then conflict with a nil value in the state and show that it needed to be updated on every apply. We now mark the allowlist name as computed so that it can update the state when it is not set.  Additionally we stop sending the value on updates unless it explicitly set in the resource.
=> fix allowlist_resource churn on empty name

.github/workflows/release.yml, CHANGELOG.md
The release process was still not working.  This change updates these actions to to the latest versions:
ghaction-import-gpg
goreleaser-action
Additionally it removes the version pinning of goreleaser and lets the action default that instead.
=> Update release related github actions

.github/workflows/release.yml, CHANGELOG.md
It seems like there is some approval process for using a later version of this and version 6 is not allowed.  For now we revert back to version 5 of this action.
=> revert ghaction-import-gpg version back to 5

.github/workflows/release.yml, CHANGELOG.md
Pin the version of go-releaser to v1
=> revert go-releaser to v1

CHANGELOG.md, README.md, docs/resources/allow_list.md, examples/workflows/cockroach_dedicated_cluster/main.tf, internal/provider/allowlist_resource.go
Including:
* sync variables mentioned in README with actual example
* add example values for allow list name and CIDR IP
* remove limited access denotion for Azure clusters
* add link to terraform sensitive values recommendations in example comment.
=> minor textual changes to README and dedicated example

CHANGELOG.md, internal/provider/private_endpoint_services_resource.go, internal/provider/private_endpoint_services_resource_test.go
Previously, when reading the `private_endpoint_services` resource for AWS the clusters, the '.aws' field remained unset, despite expectations otherwise. This commit fixes the bug to ensure that field remains set.
=> private_endpoint_services: fix backwards compat bug

CHANGELOG.md, docs/resources/private_endpoint_connection.md, examples/resources/cockroach_private_endpoint_connection/resource.tf
Previously, the private_endpoint_connection resource examples was using the private_endpoint_services resource incorrectly.  This change fixes that and updates the generated documentation.
=> fix incorrect endpoint services examples

CHANGELOG.md, docs/resources/user_role_grants.md, examples/resources/cockroach_user_role_grants/resource.tf, internal/provider/user_role_grants_resource.go
Previously, it was unknown that ORG_MEMBER was required to be passed. Ideally this would not be the case but as a quick fix, we update the docs and examples to indicate that it is required.
=> updated user_role_grants docs

CHANGELOG.md, docs/resources/private_endpoint_connection.md, docs/resources/private_endpoint_services.md, examples/resources/cockroach_private_endpoint_connection/resource.tf, examples/workflows/aws_privatelink/main.tf, internal/provider/models.go, internal/provider/private_endpoint_services_resource.go, internal/provider/private_endpoint_services_resource_test.go, vendor/github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier/doc.go, vendor/github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier/requires_replace.go, vendor/github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier/requires_replace_if.go, vendor/github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier/requires_replace_if_configured.go, vendor/github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier/requires_replace_if_func.go, vendor/github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier/use_state_for_unknown.go, vendor/modules.txt
Previously, the private_endpoint_services resource contains the regional services in a list. This made it hard for users to access the service for a given region. This commit adds a service map that contains all the services but are keyed by the cloud region.
=> provider: add services map to private_endpoint_services

CHANGELOG.md, README.md, docs/resources/private_endpoint_connection.md, docs/resources/private_endpoint_services.md, internal/provider/private_endpoint_connection_resource.go, internal/provider/private_endpoint_services_resource.go
Adding a warning to the README about the need to use a recent version of the provider for private endpoints to avoid a recently discovered bug in older versions.
=> Adding a warning to the README about the need to use a recent version of the provider for private endpoints 

examples/workflows/cockroach_folder/main.tf, examples/workflows/cockroach_serverless_cluster/main.tf, examples/workflows/cockroach_user_role_grants/main.tf, internal/provider/cluster_resource_test.go
Add tests for downgrading from the STANDARD plan to the BASIC plan.
=> add downgrade tests from STANDARD to BASIC

DEVELOPMENT.md, internal/provider/cluster_resource_test.go, internal/provider/user_role_grant_resource_test.go, internal/provider/user_role_grants_resource_test.go
Previously, the top level terraform user was used for testing in the user_role_grant_resource and user_role_grants_resource tests. Changes to this user are fragile and could affect other tests or require manual fixing on failure. This commit updates the user associated with those tests to be a newly created service account user. Additionally this commit also includes a new acceptance test for
user_role_grants_resource.
Checklist is unnecessary since the changes only affect tests
=> [CC-29279] improve user_role_grant/s testing with sa user

internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go, internal/provider/service_account_resource.go
Previously, the Plan field was not passed to the CreateCluster API, even if
it was explicitly set by the user. This prevented the server from validating
the cluster configuration. For example, the server was not able to return
an error when Plan=BASIC and provisioned_vcpus are set. The fix is to pass
the Plan field to CreateCluster if the user explicitly sets it.
=> pass Plan to CreateCluster if it was specified by the user

CHANGELOG.md, docs/data-sources/cluster.md, docs/resources/cluster.md, examples/resources/cockroach_cluster/resource.tf, examples/workflows/cockroach_standard_cluster/main.tf, internal/provider/allowlist_resource_test.go, internal/provider/cluster_data_source.go, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go, internal/provider/database_resource_test.go, internal/provider/models.go, internal/provider/private_endpoint_connection_resource_test.go, internal/provider/private_endpoint_services_resource_test.go, internal/provider/sql_user_resource_test.go
upgrade_type is now added for BASIC and STANDARD clusters.  It can be used to dictate how the cluster handles major version upgrades.  Valid values for upgrade_type are AUTOMATIC and MANUAL.  BASIC clusters support only AUTOMATIC upgrades.
=> Add upgrade_type attribute to cluster resource

docs/data-sources/cluster.md, docs/resources/cluster.md, internal/provider/cluster_data_source.go, internal/provider/cluster_resource.go
Note that the upgrade_type docs in the cluster data source were not updated as part of this change and remain:
"Dictates the behavior of cockroach major version upgrades."
The reason for this is that the remainder that was added seemed only to pertain to setting the values and not for reading them back.
=> update docs for cluster_resource upgrade_type

CHANGELOG.md, internal/provider/cluster_resource.go
Previously the api didn't allow deletion of locked clusters.  It now does so waiting for the lock before deleting is just adding extra time to apply the changes.  We now issue the delete right away.
=> [CC-30294] don't wait for lock before cluster deletion

CHANGELOG.md, docs/resources/client_ca_cert.md, docs/resources/cluster.md, docs/resources/cmek.md, docs/resources/folder.md, docs/resources/jwt_issuer.md, docs/resources/log_export_config.md, docs/resources/maintenance_window.md, docs/resources/metric_export_cloudwatch_config.md, docs/resources/metric_export_datadog_config.md, docs/resources/metric_export_prometheus_config.md, docs/resources/version_deferral.md, examples/resources/cockroach_aws_private_endpoint_connection/resource.tf, examples/resources/cockroach_client_ca_cert/import.sh, examples/resources/cockroach_cluster/import.sh, examples/resources/cockroach_cmek/import.sh, examples/resources/cockroach_cmek/resource.tf, examples/resources/cockroach_folder/import.sh, examples/resources/cockroach_jwt_issuer/import.sh, examples/resources/cockroach_log_export_config/import.sh, examples/resources/cockroach_maintenance_window/import.sh, examples/resources/cockroach_metric_export_cloudwatch_config/import.sh, examples/resources/cockroach_metric_export_datadog_config/import.sh, examples/resources/cockroach_metric_export_prometheus_config/import.sh, examples/resources/cockroach_version_deferral/import.sh
The docs plugin adds a section to each each resource indicating the support of Import based on the existence of an import.sh example. This file was missing for some resources despite the actual support of the Import action. The missing files are added here and docs are regenerated.
=> Added missing import.sh files and generate docs

CHANGELOG.md, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go
Previously, the cluster create and update operations would validate the parent_id manually via a separate API call.  This validation is also done within the create and update api calls so these additional calls were unnecessary.  We remove them here and add tests around setting this value which were previously missing.
=> [CC-30315] rely on cluster api for validating parent_id

.github/workflows/acceptance-tests.yml
This action is very similar to the pre-release-ci action which runs when a tag is created, but it can be triggered manually on any branch. This allow us to easily run the acceptance tests in other convenient times such as before landing a branch or before creating a tag.
=> Add a github action for triggering acceptance tests

CHANGELOG.md, docs/resources/cluster.md, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go
STANDARD clusters now accept the cockroach_version attribute on cluster update for manual upgrades control.  The serverless.upgrade_type attribute must be set to MANUAL.
As part of this an API call to validate cockraoch_version for ADVANCED clusters prior to the update was removed.  This logic provided some nicer error messages for advanced clusters but the logic was complex, it required an additional api call to fetch the valid versions and standard tier version checking is not supported.  We now rely on the serverside validation for checking versions.
=> [CC-30640] allow manual version control for standard clusters

CHANGELOG.md, docs/resources/cluster.md, docs/resources/cmek.md, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go
Previously it was possible to pass in the node_count value for serverless region because the type is shared with dedicated clusters. This ended up causing a state inconsistency however becase node_count is coerced to 0 by the api which conflicts with a value added in the config. To solve this, we simply validate that node_count is not used unless cluster plan is Advanced.
=> [CC-30768] don't allow node_count for serverless cluster

CHANGELOG.md, docs/resources/maintenance_window.md, internal/provider/maintenance_window.go, internal/provider/maintenance_window_test.go
Previously there was no indication that maintenance windows are not supported for Basic or Standard clusters.  We update the documentation here to reflect that and add a test showing that attempting to use maintentance windows with a non-Advanced cluster will fail.
=> [CC-30770] document maintenance windows are Advanced only

CHANGELOG.md, docs/resources/cluster.md, examples/resources/cockroach_cluster/resource.tf, examples/workflows/aws_privatelink/main.tf, examples/workflows/cockroach_client_ca_cert/main.tf, examples/workflows/cockroach_cmek/aws/main.tf, examples/workflows/cockroach_cmek/gcp/main.tf, examples/workflows/cockroach_log_export_config/aws_cockroach_log_export_config/main.tf, examples/workflows/cockroach_log_export_config/gcp_cockroach_log_export_config/main.tf, examples/workflows/cockroach_metric_export/aws/main.tf, examples/workflows/cockroach_metric_export/gcp/main.tf, internal/provider/cluster_resource.go
machine_type is not recommended for usage so we remove it from the examples and replace it with num_virtual_cpus instead.
=> [CC-30769] remove machine_type from examples

.github/workflows/acceptance-tests.yml, .github/workflows/ci.yaml, .github/workflows/pre-release-ci.yaml, CHANGELOG.md, docs/resources/allow_list.md, internal/provider/allowlist_resource.go, internal/provider/allowlist_resource_test.go
Previously the object the api returned for created and updated allowlist entries was ignored when updating the terraform state.  This meant that defaults set on the server side and returned were not correctly being set and could cause state inconsistencies in case they were different. Specifically there was a case where not setting an initial value for the create would return an empty string.  The empty string caused a state consistency error with the unset value.
To fix this we now set the state based on the response.  Also, part of this the code was reworked to be more similar to how other resources are structured.
Tests were added to show that creating an allowlist without a name now succeeds.
Also, as part of this change, instances of allowList were renamed to allowlist for …
=> CC-30971: update state with allowlist api responses

CHANGELOG.md, internal/provider/allowlist_resource.go, internal/provider/allowlist_resource_test.go
In a previous commit (272cdd80b3f93b61facaffa39a886dcd368980d9), passing the allowlist name during creation of that resource was mistakenly removed.  The test excersing it was also changed such that it didn't catch that issue.  We now add back the name and augment the test so that it covers this case again.
closes #263
=> add name back to allowlist creation

internal/provider/metric_export_prometheus_config_resource_test.go
=> Fix prometheus metric export test

CHANGELOG.md, docs/data-sources/cluster.md, docs/resources/cluster.md, examples/workflows/cockroach_advanced_cluster/main.tf, examples/workflows/cockroach_basic_cluster/main.tf, examples/workflows/cockroach_standard_cluster/main.tf, internal/provider/cluster_data_source.go, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go, internal/provider/models.go
In order to orchestrate version upgrades we allow specifying the major version of the cluster in the cluster resource.  Originally the cluster data source exposed the full version string but having this value be a different format from the resource (major vs full) was causing confusion so the data source was changed to match the resource.
At this point, the full version string was not available in any resource or data source so we add it back here as "full_version".
=> [FEB-93] add cluster attribute for full version string

CHANGELOG.md, docs/data-sources/cluster.md, docs/data-sources/folder.md, docs/resources/cluster.md, docs/resources/folder.md, examples/resources/cockroach_cluster/resource.tf, examples/resources/cockroach_folder/resource.tf, examples/workflows/cockroach_advanced_cluster/main.tf, examples/workflows/cockroach_basic_cluster/main.tf, examples/workflows/cockroach_folder/main.tf, examples/workflows/cockroach_standard_cluster/main.tf, internal/provider/cluster_data_source.go, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go, internal/provider/folder_data_source.go, internal/provider/folder_resource.go, internal/provider/folder_resource_test.go, internal/provider/models.go, internal/provider/utils.go, internal/utils/utils.go, internal/validators/labels.go
This commit adds support for managing labels through the cockroach_cluster and cockroach_folder resources in the Cockroach Terraform provider. Labels defined in Terraform are authoritative and will overwrite any labels added or removed outside of Terraform.
=> [CC-30705] add labels attribute to cluster and folder resources

internal/provider/cluster_resource.go, internal/provider/folder_resource.go
When the resource has some labels set on it, a terraform refresh will update the state. When a resource has no labels set on it in terraform, a terraform refresh does not update the state. This commit fixes this inconsistent behavior.
=> [CC-32431] fix inconsistent refresh behavior for labels

CHANGELOG.md, docs/resources/log_export_config.md, docs/resources/metric_export_cloudwatch_config.md, examples/resources/cockroach_log_export_config/resource.tf, examples/resources/cockroach_metric_export_cloudwatch_config/resource.tf, go.mod, go.sum, internal/provider/log_export_config_resource.go, internal/provider/log_export_config_resource_test.go, internal/provider/metric_export_cloudwatch_config_resource.go, internal/provider/metric_export_cloudwatch_config_resource_test.go, internal/provider/models.go, vendor/github.com/cockroachdb/cockroach-cloud-sdk-go/v6/pkg/client/model_audit_log_action.go, vendor/github.com/cockroachdb/cockroach-cloud-sdk-go/v6/pkg/client/model_cloud_watch_metric_export_info.go, vendor/github.com/cockroachdb/cockroach-cloud-sdk-go/v6/pkg/client/model_enable_cloud_watch_metric_export_request.go, vendor/github.com/cockroachdb/cockroach-cloud-sdk-go/v6/pkg/client/model_enable_log_export_request.go, vendor/github.com/cockroachdb/cockroach-cloud-sdk-go/v6/pkg/client/model_log_export_cluster_specification.go, vendor/modules.txt
This commit implements external_id support for both CloudWatch metric export
and log export configurations. External ID is used when assuming AWS IAM
roles and provides additional security for cross-account access.
Changes:
* Upgrade cockroach-cloud-sdk-go to  v6.1.0
* Add external_id field to CloudWatch metric export resource
* Add aws_external_id field to log export resource
* Update tests for both resources
* Addresses an issue where fields incorrectly marked as computed led to
miscalculation of diffs when fields were commented out or removed from the
terraform config
* Ensures backward compatibility for existing configurations
=> add AWS external_id support for metric/log export

CHANGELOG.md, internal/provider/user_role_grant_resource.go, internal/provider/user_role_grant_resource_test.go
Previously, the external deletion of a service account resource managed in Terraform caused errors on apply if there was a user role grant resource that referenced the user ID associated with the deleted service account. This PR fixes this issue by adding a RequireReplace plan modifier on the UserID attribute of the UserRoleGrant resource.
=> [CLOUDOPS-13734] handle external deletion of service account in user role grant resource

CHANGELOG.md, docs/resources/private_endpoint_services.md, internal/provider/private_endpoint_services_resource.go, internal/provider/private_endpoint_services_resource_test.go
Previously, when waiting for private endpoints service creation, the resource could be considered ready if a single resource was ready and others were not yet created. This commit fixes the bug by explicitly waiting for all regional services to be AVAILABLE.
=> private_endpoints_service: wait for all regions

CHANGELOG.md
Move the Unreleased section into a new 1.14.0 entry dated 2025-09-02. No other files were modified.
=> Update CHANGELOG for 1.14.0

CHANGELOG.md
This commit updates the release date for version 1.14.0 to 2025-09-03 in the CHANGELOG.
=> Update 1.14.0 release date in CHANGELOG

CHANGELOG.md, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go
This commit removes the `UseStateForUnknown` plan modifier from the `state` field to prevent errors when the computed field drifts due to external changes.
=> remove plan modifier from `state` field in cluster resource

CHANGELOG.md, docs/data-sources/cluster.md, docs/resources/cluster.md, docs/resources/cmek.md, internal/provider/cluster_data_source.go, internal/provider/cluster_resource.go, internal/provider/cluster_resource_test.go, internal/provider/models.go
Previously, `private_endpoint_dns` was not exposed in the cluster region list. Since it is used to connect a cluster to GCP Private Service Connect, customers needed to manually retrieve the `private_endpoint_dns` from the CockroachCloud UI or API, breaking end-to-end automation.
This change adds `private_endpoint_dns` to the cluster region list to allow customers to directly access it via Terraform.
This commit builds on #281.
=> [CNSL-1406] Expose private_endpoint_dns in cluster region list

CHANGELOG.md, internal/provider/backups_data_source_test.go, internal/provider/restore_resource_test.go, internal/provider/restores_data_source_test.go, internal/provider/utils.go
This commit involves adding an acceptance test for the cockroach_backups data source.
=> [CNSL-1482] add acceptance test for cockroach_backups data source

CHANGELOG.md
Update the CHANGELOG for the v1.15.0 release with release date 2025-09-30.
=> Update CHANGELOG for v1.15.0 release
