main.go

fix provider address

---

internal/provider/cluster_resource.go
internal/provider/networking_resource.go
internal/provider/private_endpoint_connection_resource.go
internal/provider/private_endpoint_services_resource.go
internal/provider/sql_user_resource.go
internal/provider/utils.go

Sorry for combining two separate changes into one commit. They're both straightforward though.

Updated API error format and required replace for cluster_id changes

---

.github/workflows/release.yml
Makefile

- Bumped version in makefile to 0.3.0
- Updated the release github workflow to run live acceptance tests first

0.3.0 release

---

internal/provider/cluster_resource_test.go
internal/provider/networking_resource_test.go
internal/provider/private_endpoint_connection_resource_test.go
internal/provider/private_endpoint_services_resource_test.go
internal/provider/sql_user_resource_test.go

Accidentally unset the API key before the acceptance tests could run 🤦

Fix acceptance tests

---

internal/provider/private_endpoint_connection_resource.go

Since the CCAPI job to accept endpoint connections is async, we can
get into a state where the connection still shows as PENDING_ACCEPTANCE
after it's been accepted. The old wait logic looked for ACCEPTED or
PENDING, and failed out with other statuses, including
PENDING_ACCEPTANCE. This change interprets that status the same as
PENDING, and also lowers the timeout for connections (which usually
only take a minute or less) to 5 minutes.

Work around race condition for endpoint connections

---

README.md

Add link to Terraform registry

---

go.mod
go.sum
internal/provider/cluster_resource.go
internal/provider/cmek_resource.go
internal/provider/cmek_resource_test.go
internal/provider/networking_resource.go
mock/service.go

Update the CC Go SDK to latest v0.4.0.

Update CC Go SDK to v0.4.0

---

go.mod
go.sum
internal/provider/cluster_resource.go
internal/provider/cluster_resource_test.go
internal/provider/cmek_resource_test.go
internal/provider/cockroach_cluster_data_source.go
internal/provider/database_resource.go
internal/provider/database_resource_test.go
internal/provider/networking_resource.go
internal/provider/networking_resource_test.go
internal/provider/private_endpoint_connection_resource.go
internal/provider/private_endpoint_connection_resource_test.go
internal/provider/private_endpoint_services_resource_test.go
internal/provider/sql_user_resource.go
internal/provider/sql_user_resource_test.go
internal/provider/utils.go

Two commits, one of which fixes a series of dependabot vulnerabilities by updating the `net` library, and one which addresses issue #80.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/85)

Bug and vulnerability fixes

---

internal/provider/networking_resource.go
internal/provider/networking_resource_test.go

Fixes https://github.com/cockroachdb/terraform-provider-cockroach/issues/86

Fix updating ip allowlist state 

---

go.mod
go.sum
mock/service.go

Update the Go SDK to latest v0.4.2

Update CC Go SDK to v0.4.2

---

go.mod
go.sum
mock/service.go

Update CC Go SDK to v0.4.3

---

examples/workflows/cockroach_cmek/gcp/main.tf

Added a sleep with comment, and switch from using authoratative IAM bindings to targeted memberships.

Add sleep to GCP CMEK example

---

.github/pull_request_template.md
DEVELOPMENT.md

Added a contributor guide section to DEVELOPMENT.md detailing how to run and add tests, perform a release, etc. Includes TF doc links, a general overview, and a brief Q&A with questions I've been asked recently.
Also updated the commit template with a checklist. I often forget to regenerate docs, so hopefully this will help. Someday, we'll have linters for that, but this'll work for now.

[CC-25143] Contributor guide

---

docs/resources/log_export_config.md
examples/resources/cockroach_log_export_config/cockroach_log_export_config.tf
examples/workflows/cockroach_log_export_config/aws_cockroach_log_export_config/main.tf
examples/workflows/cockroach_log_export_config/gcp_cockroach_log_export_config/main.tf
internal/provider/log_export_config_resource.go
internal/provider/log_export_config_resource_test.go
internal/provider/models.go

This change updates `LogExport` to include `omitted_channels`

[CC-25438] Update `LogExport` to include `omitted_channels`

---

CHANGELOG.md

This depends on #160 and #159.
---
This commit updates the CHANGELOG.md file for the upcoming v1.2.0 release.

Update changelog for v1.2.0 release 

---

CHANGELOG.md

Update changelog for v1.3.0 release

---

CHANGELOG.md
Makefile
docs/data-sources/cluster.md
docs/resources/cluster.md
internal/provider/cluster_data_source.go
internal/provider/cluster_resource.go
internal/provider/cluster_resource_test.go
internal/provider/models.go

support backwards-compatible serverless attribute

---

CHANGELOG.md

changelog: prep 1.3.1 release

---

examples/workflows/cockroach_standard_cluster/main.tf

Adding a new workflow to help Private Preview Standard customers

adding workflow for standard

---

CHANGELOG.md

CHANGELOG: v1.3.2 release

---

DEVELOPMENT.md

Some random improvements to the DEVELOPMENT.MD file including:
* Add a section on using a debugger
* update qaserver example url to apiserver
* update question section to refer to Console team instead of App Platform

improvements to DEVELOPMENT.md

---

internal/provider/private_endpoint_services_resource_test.go

There are less limitations on GCP hosts so we prefer to use those for spinning up dedicated tests where possible.  This updates the the dedicated test in the private_endpoint_services_resource test to use GCP.

Use GCP in private_endpoint_services_resource test for dedicated

---

DEVELOPMENT.md

Fix some typos in DEVELOPMENT.md

---

internal/provider/metric_export_prometheus_config_resource_test.go

[CC-26984] metric-export: fix prometheus integration test

---

.github/workflows/release.yml
CHANGELOG.md
internal/provider/cluster_resource_test.go

Fix go releaser

---

CHANGELOG.md

release v1.7.7

---

.github/workflows/ci.yaml

Allow running the pre-release-ci job manually

---

CHANGELOG.md
docs/resources/cluster.md
internal/provider/cluster_resource.go

Clarify dedicated advanced setting

---

internal/provider/metric_export_prometheus_config_resource_test.go

This reverts commit c67e8c29c48c8420eb55ccca7f8474fe537b176f.

Revert "metric-export: remove update flow from integration test of prometheus

---

internal/provider/cluster_resource_test.go
internal/validators/labels.go

This commit updates the label validation message to mention all the requirements for valid labels.

[CC-32432] update label validation message

---

internal/provider/cluster_resource_test.go

Change latest cluster version in cluster resource test

---

CHANGELOG.md
docs/data-sources/cluster.md
docs/resources/cluster.md
internal/provider/cluster_data_source.go
internal/provider/cluster_resource.go
internal/provider/cluster_resource_test.go
internal/provider/models.go
internal/provider/physical_replication_stream_test.go

Add support_physical_cluster_replication flag to Cluster

---

README.md

Added section for reporting bugs and requesting features.

Document bug reporting and feature request process
